### PR TITLE
ReiNX menu

### PR DESCRIPTION
**Pull request by Guillem96**
# ReiNX Menu

## Why this menu? 

My idea is to create a simple menu which can be launched during ReiNX payload injection.

This menu will integrate some functionalities of hekate and maybe in a near future this menu can be the entry point to create the EmuNAND.

I think this is helpful because using to different payloads to perform some actions is tedious, it is always better having all the functionalities integrated in one package(in this case, one payload).

## Menu look
The menu looks like this:

menu

## Future plans

- Improve UI
- Add dump/restore NAND and BOOT0/1
- Add more functionalities

## How to launch the menu?

```
Hold VOLUME UP BUTTON while ReiNX is starting
```

### CODE REVIEW

**Comment by Reisyukaku** [comment]
This completely negates the purpose of the toolkit.

**Comment by neonsea** [comment]
I like it! However...

I was working on basically the exact same thing as this for a while but then I realized that this is kind of redundant - most ReiNX functionality is fit into the Toolkit, everything else is p. much done by Hekate (which can in turn boot ReiNX). 

Don't get me wrong, I like it and I see you've put quite a bit of work into this but maintaining this code that we don't exactly need is extra effort.

**Comment by Reisyukaku** [comment]
I'm thinking of maybe a recovery feature that can be loaded externally and is optional

**Comment by Guillem96** [comment]
The toolkit has some pros, for example dumping the nand it is at least 20 minutes faster, but this menu allows you to have the toolkit functionalities without entering to horizon and this mean that you can perform some actions without generating logs about them and consequently reduce the ban risk.
Maybe it is better to leave the menu as a recovery menu and only have the unctionalities as nand restore, chek burnt fuses...

**Comment by Ch0cola** [comment]
I think it's a nice idea have a previous loader and can bring good things to ReiNX toolkit too.

For example, with a minimal payload (recovery like this), it's possible add the main payload (current ReiNX.bin) to SD and autoboot it, this allow make autoinstaller and make possible the auto updater through toolkit too.

In my case, I use always Hekate like a boot loader and I have configured ReiNX payload as autoboot from SD, if I don't touch any key on power on, boot automatically to ReiNX, if i press VOL -, bring me the hekate menu with all of his features and my configured launchers.

Think on it like a BIOS, if I found a good solution to block all networking and only allow connections to builds.reinx.guide I can work on this feature if the first preloader (one thing like this PR) are available and manage the SD files directly with the ReiNX toolkit homebrew to update it when a new release (or nightly) are available.

**Comment by Reisyukaku** [comment]
I would prefer a clean room solution as not to copy more hekate code either way I suppose. But like i said, preferably, we should just have  seperate recovery.bin that gets chainloaded instead of reinx.. it'll basically be like TWRP.

**Pull request closed without merging**
