### PR TITLE
clarify things in readme

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**
- This is a bootloader
- The sysmodules aren't really exclusive, they can be loaded with Hekate (plus, they are atmos' + with *some* patches)

### CODE REVIEW

**Comment by Reisyukaku** [comment]
Not these memes again. Sure the kips *can* be loaded with other cfw, but why would you want RNX patches in say hekate? the RNX patching system is exclusive. Plus I do have plans to implement some things that will only work on reinx.

**Comment by ThatNerdyPikachu** [comment]
``but why would you want RNX patches in say hekate``

Customization? More features than ReiNX at the moment? Just preferences of the user?

**Comment by ThatNerdyPikachu** [comment]
Also, ``Not these memes again``? It's the truth at the moment 🤔

**Comment by Enscivwy** [comment]
Top 10 most epic anime fights...literally

**Comment by ThatNerdyPikachu** [comment]
ensci no

**Comment by psfree** [comment]
Why would you do this? Its incredibly rude to come out of nowhere and make a passive aggressive PR like this. We work hard to create this software and we provide it for free and allow anyone to modify and use as they see fit. We follow the licenses of all software we used to build ReiNX and give credit where it is due. We get no benefit by working on this other than the joy it brings to those that use it.

Not sure what you are talking about when you say Hekate has more features than ReiNX. We are aiming for a different audience and therefore have tailored our software to what we think best suits that audience. If you feel like Hekate is better for you then great!  If you are a software developer please go and contribute because I'm sure they would love the help! 

Whats not useful to anyone though is slinging mud at other people and their hard work. If you don;t like ReiNX or its features you are welcome to not use it. The beauty of competition is that everyone benefits from it and the beauty of open source is that developers can learn and share with one another. We just want to make the scene as good as it possible can be, not get in flamewars about which cfw is better.

Lastly its completely untrue that Hekate is universally better than ReiNX off the top of my head I can name 2 things I have personally contributed that are not available in Hekate and those are:
1. Patches to allow custom NSP loading on ALL firms.
2. Nand dumping in 15 minutes

Right now hekate has neither.

**Comment by ThatNerdyPikachu** [comment]
``We are aiming for a different audience``
What kind of audience? (What specifically do you mean by that?)

**Comment by Reisyukaku** [comment]
This isn't going anywhere clearly.

**Comment by psfree** [comment]
Well I will give you an example. We designed ReiNX to not have menus or config files. We want to make a cfw that "just works" for the average user with a minimum of messing around. Another thing I find our users like is that we don't prevent them from doing things they wish with the console that they own. While I personally don't pirate I feel that its not my place to push my morality on others. I believe that computers should be open platforms and that people should be free to run whatever code they want even if it has potential downsides.

**Comment by psfree** [comment]
The ReSwitched developers actually considered adding DRM to layeredfs to prevent piracy. Hekate and RajNX both refused to include NSP patches because of the potential to load pirated NSPs. 

I'm not sure if you've ever been in the ReSwitched discord but they ban people for even breathing something they disagree with. On the ReiNX server we don't ban people who have different opinions. You are welcome to join even though you seem to have disagreements. Ultimately we believe that freedom is the best option and we practice what we preach. You are welcome to come on the discord and call me a big dumb doodoo head if you wish. Its our attitude that is different as well.

**Comment by Reisyukaku** [comment]
Take the cfw wars elsewhere.

**Pull request closed without merging**
