### PR TITLE
Skip *nix hidden files

### PR DESCRIPTION
**Pull request by AnalogMan151**
Skips files with leading period for *nix and macOS

### CODE REVIEW

**Comment by Reisyukaku** [comment]
Only thing I'm concerned with is it assumes that those files are the last files in the list. Cant find where it says what order fatfs goes in

**Comment by AnalogMan151** [comment]
Ah, good point. It stops the loop as soon as it encounters a file leading with period. It would be better to put the check inside of the loop like so:
```c
    int i; for (i = 0; (fno.fname[0] != 0 && fno.fname[0] != '.') && fr == FR_OK; i++) {
        if (fno.fname[0] == '.')
            continue;
        out = (char **)realloc(out, (i+1) * sizeof(char *));
        out[i] = (char *)malloc(FF_LFN_BUF);
        strcpy(out[i], pathb);
        strcat(out[i], fno.fname);
        pathb[pathlen+1] = 0;
        f_findnext(&dp, &fno);
    }
````

**Comment by AnalogMan151** [comment]
Tested this out and it appears to work but I would like you opinion:
```c
    int i = 0; 
    while (fno.fname[0] != 0 && fr == FR_OK) {
        if (fno.fname[0] == '.') {
            f_findnext(&dp, &fno);
            continue;
        }   
        out = (char **)realloc(out, (i+1) * sizeof(char *));
        out[i] = (char *)malloc(FF_LFN_BUF);
        strcpy(out[i], pathb);
        strcat(out[i], fno.fname);
        pathb[pathlen+1] = 0;
        f_findnext(&dp, &fno);
        i++;
    }
```
Here is the file list in my sys modules folder:
```
._FS.kip
._loader.kip
._sm.kip
FS.kip
loader.kip
sm.kip
```
Without the edit my Switch will stall on launching when those files are encountered.

**Comment by Reisyukaku** [comment]
`if (fno.fname[0] == '.') continue;`
should work just fine i'd think

**Comment by AnalogMan151** [comment]
I thought that too but that increments `i` and also does not advance the `fno.fname` to the next entry (meaning it would just process the same filename over and over). If you did advance to next `fno.fname` with `i` incrementing it would leave empty `out[]` entries when it runs into one of the hidden files. With the while loop `i` is only incremented when a non-hidden file is found.

**Comment by Reisyukaku** [comment]
Ah right, in that case maybe this would be cleaner:
```C
int i = 0; 
    while (fno.fname[0] != 0 && fr == FR_OK) {
        if (fno.fname[0] == '.') goto end;  
        out = (char **)realloc(out, (i+1) * sizeof(char *));
        out[i] = (char *)malloc(FF_LFN_BUF);
        strcpy(out[i], pathb);
        strcat(out[i], fno.fname);
        pathb[pathlen+1] = 0;

       end:
        f_findnext(&dp, &fno);
        i++;
    }
```

**Comment by AnalogMan151** [comment]
That still increments `i` when a hidden file is processed leaving an empty entry in the array. This perhaps?

```c
int i = 0; 
    while (fno.fname[0] != 0 && fr == FR_OK) {
        if (fno.fname[0] == '.') goto end;  
        out = (char **)realloc(out, (i+1) * sizeof(char *));
        out[i] = (char *)malloc(FF_LFN_BUF);
        strcpy(out[i], pathb);
        strcat(out[i], fno.fname);
        pathb[pathlen+1] = 0;
        i++;
       end:
        f_findnext(&dp, &fno);
    }
```

**Comment by Reisyukaku** [comment]
Oh derp. Didnt fully read. Yea, that looks good.

**Comment by AnalogMan151** [comment]
Fix added to pul request.

**Pull request merged**
